import "./global.css";
import { Inter } from "next/font/google";
import Navbar from "@app/_layout/navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/next-favicon.png"
          type="image/x-icon"
        />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <body suppressHydrationWarning={true}>
        <Navbar /> {children}
      </body>
    </html>
  );
}
