import "./_styles/global.css";
import Navbar from "@app/_layout/navbar";
import Body from "@app/_layout/body";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="/next-favicon.png"
          type="image/x-icon"
        />
        <meta name="description" content={metadata.description} />
        <title>{metadata.title}</title>
      </head>
      <Body>
        <Navbar /> {children}
      </Body>
    </html>
  );
}
